//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankingSystem
{
    using PropertiesChangedLib;
    using System;
    using System.Collections.Generic;
    
    public partial class Client : PropertiesChanged
    {
        public int Id { get; set; }
        public string clientName { get; set; }
        public string clientLastname { get; set; }
        public string clientPatronymic { get; set; }
        public int clientAge { get; set; }
        public string clientType { get; set; }
        public Nullable<long> cardNumber { get; set; }
        public Nullable<int> bankBalance { get; set; }
        public string checkingAccount { get; set; }
        public Nullable<int> accountBalance { get; set; }
    }
}
