//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public string NameTarget { get; set; }
        public string LastnameTarget { get; set; }
        public string PatronymicTarget { get; set; }
        public Nullable<long> CardTarget { get; set; }
        public string CheckingAccount { get; set; }
        public string ClientTypeTarget { get; set; }
        public int TransactionSum { get; set; }
        public int Type { get; set; }
    }
}
